steps:
- name: 'python:3.8.7-slim'
  dir: .
  entrypoint: /bin/sh
  args:
    - -c
    - 'pip install -U platformio'
    - 'platformio run'
artifacts: 
  objects: 
    location: 'gs://$PROJECT_ID-firmwares/$TAG_NAME'
    paths: ['/workspace/.pioenvs/esp32/firmware_esp32.bin','/workspace/.pioenvs/esp8266/firmware_esp8266.bin']