steps:
- name: 'python:3.8.7-slim'
  id: INSTALL
  entrypoint: python3
  dir: .
  args:
    - -c
    - 'pip install -U platformio'
- name: python:3.8.7-slim
  id: RUN
  entrypoint: python3
  dir: .
  args:
  - 'platformio run'
  waitFor:
  - INSTALL
artifacts: 
  objects: 
    location: 'gs://$PROJECT_ID-firmwares/$TAG_NAME'
    paths: ['/workspace/.pioenvs/esp32/firmware_esp32.bin','/workspace/.pioenvs/esp8266/firmware_esp8266.bin']