steps:
- name: 'infinitecoding/platformio-for-ci:latest'  
  dir: .
  args: ['run -d /workspace/']  
artifacts: 
  objects: 
    location: 'gs://$PROJECT_ID-firmwares/$TAG_NAME'
    paths: ['/workspace/.pioenvs/esp32/firmware_esp32.bin','/workspace/.pioenvs/esp8266/firmware_esp8266.bin']