steps:
- name: 'python:3.8.7'
  entrypoint: /bin/sh
  dir: .
  args:
  - -c
  - 'pip install platformio && platformio run'
artifacts: 
  objects: 
    location: 'gs://$PROJECT_ID-firmwares/$TAG_NAME'
    paths: ['.pio/build/esp32/firmware_esp32.bin','.pio/build/esp8266/firmware_esp8266.bin']
